In [1]:
import numpy as np

In [4]:
arr = np.linspace(1, 10, 10, dtype='int8') # creavalores random entre 1 y 10, con un total de 10 valores y que sea tipo int8
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [6]:
indices_cond = arr > 5 # Regresa una lista boolean de quienes cumplen la condicion
indices_cond

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [7]:
arr[indices_cond]  # ? Solo devuelve los valores que esten en TRUE, cumplen con la condicion anterior

array([ 6,  7,  8,  9, 10], dtype=int8)

In [9]:
arr[(arr > 5) & (arr < 9)]

array([6, 7, 8], dtype=int8)

In [11]:
arr[arr > 5 ] = 99  # los valores mayores a 5 se cambiaran a 99
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

In [14]:
matriz = np.array([[19, 4, 32], [8, 96, 80], [6, 99, 35]])
matriz

array([[19,  4, 32],
       [ 8, 96, 80],
       [ 6, 99, 35]])

In [15]:
np.where(matriz > 50, 0, 1)  # ? where(Condicion, valor en True, valor en False)

array([[1, 1, 1],
       [1, 0, 0],
       [1, 0, 1]])