In [11]:
import numpy as np

In [12]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
trozo_de_array = arr[0: 6]

In [14]:
trozo_de_array

array([0, 1, 2, 3, 4, 5])

In [15]:
trozo_de_array[:] = 0  # ? Cambiamos todos los valores del array a "0"
trozo_de_array  # todo: Este metodo CAMBIA el array original

array([0, 0, 0, 0, 0, 0])

In [16]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [17]:
arr_copy = arr.copy()  # ! .copy(), copia el array y deja el original intacto 

In [18]:
arr_copy[:] = 100

In [19]:
arr_copy  # * el nuevo array NO afecta al original

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [20]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])