In [21]:
import numpy as np

In [22]:
list(range(0, 10, 2))  # array generado al estilo python

[0, 2, 4, 6, 8]

In [23]:
np.arange(0, 20, 2)  # ? array generado con numpy

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [24]:
np.zeros((5, 10))  # ? .zeros(), Es usado para definir estructuras de matrices previas usando 0.

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [25]:
np.ones((5, 10))  # ? .ones(), se usa para lo mismo que .zeros()

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [26]:
np.linspace(0, 10, 20)  # ? .linspace(), 0: es el inicio, 10: es el dato final, 20: cuandos datos deben haber entre el 0 y el 10

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [27]:
np.eye(4)  # ? .eye() crea una matriz de n*n y la diagonal central estara llena de 1

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
np.random.rand()  # * genera un numero aleatorio

0.08301604467788992

In [29]:
np.random.rand(4)  # ? genera un array de 'n' valores aleatorios. ( 1 dimension)

array([0.58724229, 0.27162287, 0.66375167, 0.95571415])

In [30]:
np.random.rand(4, 4)  # ? genera una matriz de 'n*n' con valores aleatorios ( 2 dimensiones)

array([[0.04424668, 0.13422032, 0.5570255 , 0.26140658],
       [0.44158635, 0.77840586, 0.19126658, 0.89427452],
       [0.18157213, 0.85775156, 0.28539904, 0.69142548],
       [0.28219831, 0.57796205, 0.55025107, 0.59177438]])

In [31]:
np.random.randint(1, 20)  # ? genera un entero aleatorio entre 'n' y 'm'

11

In [35]:
np.random.randint(1, 100, (10, 10))  # ? Genera valores aleatorios enteros entre 1 y 100, con una matriz de 10*10

array([[98, 44, 88, 60, 26, 62, 41, 95, 93, 35],
       [60, 95, 26, 93, 13, 64, 58, 47, 71,  9],
       [71, 50, 63, 77, 83, 40, 16, 49, 21, 44],
       [62, 64, 18, 92, 80, 96, 37, 63, 58, 30],
       [84, 74, 70, 47, 83,  3, 65, 11, 64, 38],
       [75, 29, 12, 45, 93, 65, 94, 63, 45, 83],
       [42, 46,  5, 23, 31, 80, 73, 58, 97, 28],
       [35, 43, 91, 30, 20, 61, 65, 10, 88, 97],
       [ 7, 25, 73, 40, 10, 85, 51,  8, 83, 45],
       [14, 87, 28, 70,  7, 19, 24, 15, 40,  4]])