In [1]:
import numpy as np

In [2]:
lista = [1, 2]
lista

[1, 2]

In [3]:
lista * 2 # Esto NO hace lo que buscamos, NO multiplica los valores de la lista * 2, solo duplica los elementos

[1, 2, 1, 2]

In [6]:
arr = np.arange(0, 10)
arr2 = arr.copy()

In [7]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr * 2  # Aqui SI logramos multiplicar el valor de los elementos * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
arr + 2 # Logramos sumar cada elemento del array

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
1 / arr  # todo: solo lanza un warning por la division de 0. Pero no detiene el resto del proceso

/tmp/ipykernel_23094/1528351372.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [11]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [13]:
print(arr)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [12]:
arr + arr2 # todo: Se pueden hacer operaciones con los indices de cada array. 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
arr * arr2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [15]:
matriz = arr.reshape(2, 5)
matriz2 = matriz.copy()
print(matriz)
print(matriz2)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [16]:
matriz + matriz2  # ? La suma actua en la misma posicion indexada en las matrices

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [17]:
matriz2 - matriz

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [18]:
np.matmul(matriz, matriz2.T)  # ? Operacion de producto punto

array([[ 30,  80],
       [ 80, 255]])

In [19]:
matriz @ matriz2.T  # .T, es la transpuesta de la matriz # ? Eso da el mismo resultado que arriba

array([[ 30,  80],
       [ 80, 255]])