In [1]:
import numpy as np

In [3]:
arr = np.random.randint(1, 10, (3, 2))
arr

array([[3, 6],
       [3, 5],
       [2, 2]])

In [4]:
arr.shape  # ? .shape: nos dice el numero de filas y columnas que tiene una matriz

(3, 2)

In [5]:
arr.reshape(1, 6)  # ? .reshape(): cambia la dimension de la matriz (1 fila, 6 columnas)

array([[3, 6, 3, 5, 2, 2]])

In [8]:
np.reshape(arr,(1, 6))  # ? Otra forma de hacer reshape

array([[3, 6, 3, 5, 2, 2]])

In [10]:
arr

array([[3, 6],
       [3, 5],
       [2, 2]])

In [11]:
np.reshape(arr,(2, 3), 'C')  # ? hace el reshape de la matriz como lo haria en lenguaje C, (se guira usando filas)

array([[3, 6, 3],
       [5, 2, 2]])

In [12]:
np.reshape(arr,(2, 3), 'F') # ? reshape usando 'Fortrant', (se guia usando las columnas)

array([[3, 2, 5],
       [3, 6, 2]])

In [13]:
np.reshape(arr, (2, 3), 'A')  # ? reshape usando 'A' (como mejor este obtimizado mi sistema)

array([[3, 6, 3],
       [5, 2, 2]])