In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
trozo_de_array = arr[0: 6]

In [4]:
trozo_de_array

array([0, 1, 2, 3, 4, 5])

In [5]:
trozo_de_array[:] = 0  # ? Cambiamos todos los valores del array a "0"
trozo_de_array  # todo: Este metodo CAMBIA el array original

array([0, 0, 0, 0, 0, 0])

In [6]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [7]:
arr_copy = arr.copy()  # ! .copy(), copia el array y deja el original intacto 

In [8]:
arr_copy[:] = 100

In [9]:
arr_copy  # * el nuevo array NO afecta al original

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [10]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])