In [1]:
import numpy as np

In [3]:
scalar = np.array(42)  # * un scalar es un unico valor, no tiene ninguna dimension.
print(scalar)
scalar.ndim # 0 dimensiones  # ? ndim, nos dice el numero de dimensiones del objeto 

42


0

In [4]:
vector = np.array([1, 2, 3, 4])  # * un vector, es un objeto de 1 dimension
print(vector)
vector.ndim # 1 dimension

[1 2 3 4]


1

In [7]:
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [0, 20, 35]])  # * una matriz son varios arrays, tienen 2 dimensiones
print(matriz)
matriz.ndim # 2 dimensiones  # ? ndim, nos dice el numero de dimensiones del objeto 

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 0 20 35]]


2

In [10]:
tensor = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]]])  # * una tensor son varios arrays, tienen 3 o mas dimensiones. Es una matriz dentro de otra matriz
print(tensor)
tensor.ndim # 3 dimensiones

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


3

Agregar o eliminar dimensiones