In [1]:
import numpy as np

In [2]:
scalar = np.array(42)  # * un scalar es un unico valor, no tiene ninguna dimension.
print(scalar)
scalar.ndim # 0 dimensiones  # ? ndim, nos dice el numero de dimensiones del objeto 

42


0

In [3]:
vector = np.array([1, 2, 3, 4])  # * un vector, es un objeto de 1 dimension
print(vector)
vector.ndim # 1 dimension

[1 2 3 4]


1

In [4]:
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [0, 20, 35]])  # * una matriz son varios arrays, tienen 2 dimensiones
print(matriz)
matriz.ndim # 2 dimensiones  # ? ndim, nos dice el numero de dimensiones del objeto 

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [ 0 20 35]]


2

In [5]:
tensor = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]]])  # * una tensor son varios arrays, tienen 3 o mas dimensiones. Es una matriz dentro de otra matriz
print(tensor)
tensor.ndim # 3 dimensiones

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


3

Agregar o eliminar dimensiones

In [6]:
vector = np.array([1, 2, 3], ndmin=10)  # ? ndmin=10: dice que el objeto tendra 10 dimensiones
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [7]:
expanded = np.expand_dims(np.array([1, 2, 3,]), axis=0) # ? 0 es a nivel de filas; 1 es a nivel de columnas; .expand_dims() Es un metodo para especificar que dimension se quiere expandir
print(expanded)
expanded.ndim # * mostrara 2 dimesiones, porque se expandio el axis 0, (dimesion al nivel de filas)

[[1 2 3]]


2

In [8]:
print(vector, vector.ndim)  # 10 dim
vector_2 = np.squeeze(vector)  # ? .squeeze(): Comprime el numero de dimensiones correcto, elimina las que no se esten usando.
print(vector_2, vector_2.ndim)  # 1 dim

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1
