In [15]:
import numpy as np

In [16]:
lista = [1, 2, 3, 4, 5, 6, 7, 8, 9]  # Esto es un array propio de python
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [17]:
arra = np.array(lista)  # ? Esto es un objeto array de numpy
type(arra)  # ? es de tipo numpy.ndarray

numpy.ndarray

In [18]:
matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]  # matriz de arrays
matriz = np.array(matriz)  # convirtiendo a array numpy
matriz  # asi imprimimos la matriz numpy

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
arra

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Index  

In [20]:
arra[1]

2

In [21]:
arra[0] + arra[5]  # ? El automaticamente entra, extrae el valor, y hace la operacion

7

In [22]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
matriz[0]  # Esto nos lleva al primer array dentro de la matriz

array([1, 2, 3])

In [24]:
matriz[0, 2]  # array en indice 0, y de ese array el elemento en el indice 2

3

In [25]:
arra

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Slincing 

In [26]:
arra[0:3]  # ? toma los valores desde el indice 0 hasta el 3, el indice 3 es exclusivo.

array([1, 2, 3])

In [27]:
arra[2:]  # ? arranca desde el index 2 hasta el final

array([3, 4, 5, 6, 7, 8, 9])

In [28]:
arra[::2] # ? arranca desde el 0 hasta el final, en pasos de 2 en 2   

array([1, 3, 5, 7, 9])

In [29]:
arra[-1]  # trae el ultimo indice del array 

9

In [30]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
matriz[1:]  # toma desde el segundo array de la matriz

array([[4, 5, 6],
       [7, 8, 9]])

In [32]:
matriz[1:,0:2]  # ? toma desde el array en el index "1" (filas), y el slicing desde el index 0 al 2, pero el 2 se excluye. solo llega al indez 1, (columnas)

array([[4, 5],
       [7, 8]])