In [74]:
import numpy as np

In [75]:
arr = np.random.randint(1, 20, 10)  # Numeros aleatorios del 1 al 20 y que tenga solo 10 valores en total

In [76]:
matriz = arr.reshape(2, 5)
matriz

array([[13, 15, 14,  3, 18],
       [ 7,  1, 12, 17, 10]])

In [77]:
arr

array([13, 15, 14,  3, 18,  7,  1, 12, 17, 10])

In [78]:
arr.max()  # ? Trae el valor mayor del array 

18

In [79]:
matriz.max()  # ? Trae el valor mayor de la matriz

18

In [80]:

matriz

array([[13, 15, 14,  3, 18],
       [ 7,  1, 12, 17, 10]])

In [81]:
matriz.max(1) # ? 0 nivel e filas, 1 nivel columnas. Trae el valor maximo a nivel de columnas

array([18, 17])

In [82]:
matriz.max(0)  # valores maximos a nivel de filas

array([13, 15, 14, 17, 18])

In [83]:
arr.argmax()  # ? Muestra el INDICE donde se encuentra el valor mas grande del array

4

In [84]:
matriz.argmax()

4

In [85]:
arr.min()  # ? trave el valor minimo del array

1

In [86]:
matriz.min(0)  # ? valor minimo de la matriz, a nivel de FILAS

array([ 7,  1, 12,  3, 10])

In [87]:
arr.argmin()  # ? INDICE donde esta el valor minimo del arrya

6

In [88]:
matriz.argmin(1)  # ? INDICE donde se ubica el valor minimo de la matriz a nivel de COLUMNAS

array([3, 1])

In [89]:
arr

array([13, 15, 14,  3, 18,  7,  1, 12, 17, 10])

In [90]:
arr.ptp() # ? Del pico mas bajo(6) al pico mas alto (17) hay "16" de diferencia

17

In [91]:
matriz

array([[13, 15, 14,  3, 18],
       [ 7,  1, 12, 17, 10]])

In [92]:
matriz.ptp(0)

array([ 6, 14,  2, 14,  8])

In [93]:
arr.sort()
arr

array([ 1,  3,  7, 10, 12, 13, 14, 15, 17, 18])

In [94]:
np.percentile(arr, 50)  # ? devuelve el valor que se encuentra en la mitad de nuestro array

12.5

In [95]:
np.median(arr)  # Da la mediana de valores del array

12.5

In [96]:
np.median(matriz, 0)

array([ 7. ,  8.5, 11. , 13.5, 15. ])

In [97]:
np.std(arr) # ? .std(): Es la desviacion estandar del array

5.440588203494177

In [98]:
np.var(arr) #np.std(arr) ** 2 # ? la varianza .var(), es igual a la desviacion estandar elevado al cuadrado

29.6

In [99]:
np.mean(arr)  # ? Esta es la media del array, (diferente a la mediana)

11.0

In [100]:
a = np.array([[1, 2], [3, 4]])
b = np.array([5, 6])
a

array([[1, 2],
       [3, 4]])

In [101]:
print(a.ndim)  # ambos arrays tienen diferentes dimensiones
print(b.ndim)

2
1


In [105]:
b = np.expand_dims(b, axis=0)  # * Expandi las dimensiones de b en el eje '0', es decir las filas

In [106]:
print(a.ndim)  # ambos arrays tienen diferentes dimensiones
print(b.ndim)

2
2


In [107]:
np.concatenate((a,b), axis=0)  # todo: Une el array a con el b y se aunmenta el eje 0 de las filas

array([[1, 2],
       [3, 4],
       [5, 6]])

In [108]:
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [109]:
b.T  # todo: .T, es la transpuesta de una matriz, es decir cambiarle la forma, si tenemos una forma 3x2, la transpuesta es 2x3

array([[5],
       [6]])