In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1, 20, 10)  # Numeros aleatorios del 1 al 20 y que tenga solo 10 valores en total

In [4]:
matriz = arr.reshape(2, 5)
matriz

array([[17, 11,  6, 10,  3],
       [ 1,  4, 13, 10, 14]])

In [5]:
arr

array([17, 11,  6, 10,  3,  1,  4, 13, 10, 14])

In [6]:
arr.max()  # ? Trae el valor mayor del array 

17

In [7]:
matriz.max()  # ? Trae el valor mayor de la matriz

17

In [8]:

matriz

array([[17, 11,  6, 10,  3],
       [ 1,  4, 13, 10, 14]])

In [9]:
matriz.max(1) # ? 0 nivel e filas, 1 nivel columnas. Trae el valor maximo a nivel de columnas

array([17, 14])

In [10]:
matriz.max(0)  # valores maximos a nivel de filas

array([17, 11, 13, 10, 14])

In [12]:
arr.argmax()  # ? Muestra el INDICE donde se encuentra el valor mas grande del array

0

In [13]:
matriz.argmax()

0

In [14]:
arr.min()  # ? trave el valor minimo del array

1

In [15]:
matriz.min(0)  # ? valor minimo de la matriz, a nivel de FILAS

1

In [16]:
arr.argmin()  # ? INDICE donde esta el valor minimo del arrya

5

In [17]:
matriz.argmin(1)  # ? INDICE donde se ubica el valor minimo de la matriz a nivel de COLUMNAS

array([4, 0])