In [26]:
import numpy as np 

In [27]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype  # ? Esto nos muestra el tipo de dato en numpy (int64)

dtype('int64')

In [28]:
arr = np.array([1, 2, 3, 4, 5], dtype='float64')  # ? dtype='float64', asi declaramos el tipo de dato de nuestro array. (float64) se lleva mejor con redes neuronales
arr.dtype

dtype('float64')

In [29]:
arr  # * ahora los elementos tienen un punto decimal

array([1., 2., 3., 4., 5.])

In [30]:
arr = np.array([0, 1, 2, 3, 4 ])
arr = arr.astype(np.bool_)  # * .astype() Es otra forma de definir el tipo de dato: tipo boolean
arr

array([False,  True,  True,  True,  True])

In [31]:
arr = np.array([0, 1, 2, 3, 4 ])
arr = arr.astype(np.string_)  # * .astype() Cambiando a tipo string
arr

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S21')

In [32]:
arr = np.array(['0', '1', '2', '3', '4' ])
arr = arr.astype(np.int8)  # * de tipo string a tipo int8
arr

array([0, 1, 2, 3, 4], dtype=int8)