In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Slicing and indexing

In [3]:
arr[8]  # toma el elemento en el index 8

8

In [4]:
arr[1:5]  # toma el valor contenido del index 1 al index 5

array([1, 2, 3, 4])

In [5]:
arr[:5]  # toma los elementos de index 0 hasta el index 4 (5 es exclusivo)

array([0, 1, 2, 3, 4])

In [6]:
arr[5:]

array([5, 6, 7, 8, 9])

## Broadcasting

In [7]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [8]:
arr_copy = arr.copy()  # ? Se copia el array original, podemos modificarlo sin tocar el primer array.

In [9]:
arr_copy[:] = 99  # ? Selecciona todos los elementos y se transformar en 99 

In [11]:
print(arr_copy)
print(arr)

[99 99 99 99 99 99 99 99 99 99]
[100 100 100 100 100   5   6   7   8   9]


## Indexing in 2 dimmensions 

In [12]:
arr_2d = np.array([[5,10,15], [20,25,30], [35, 40, 45]])

In [13]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [19]:
arr_2d.shape  # 3 filas, 3 columnas

(3, 3)

In [20]:
arr_2d[0]  # tomara el array que esta en el index 0

array([ 5, 10, 15])

In [22]:
arr_2d[2]

array([35, 40, 45])

In [23]:
arr_2d[0,2]  # tomara la fila '0', y la columna '2'

15

In [24]:
arr_2d[:2,1:]  # ? toma arrays desde el index 0 hasta el index 1 (2 es excluido). Toma las columnas desde el index 1 hasta la ultima

array([[10, 15],
       [25, 30]])

## Conditional selections

In [26]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
arr > 4 # Regresa un numpy array de valores boolean (superiores a 4), que cumplen con la condicion

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [28]:
bool_arr = arr > 4 
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [29]:
arr[bool_arr]  # ? con esto podemos filtrar que valores pueden ser retornados (regresa solo los valores True)

array([ 5,  6,  7,  8,  9, 10])

In [30]:
arr[arr > 4]  # * es lo mismo de arriba pero mejor escrito

array([ 5,  6,  7,  8,  9, 10])