In [1]:
import numpy as np

In [2]:
mylist = [1, 2, 3]

In [3]:
type(mylist)

list

In [5]:
new_list = np.array(mylist)

In [6]:
type(new_list)

numpy.ndarray

In [8]:
my_matrix = [[1,2,3], [4,5,6], [7,8,9]]  # esto es un array anidado normal

In [9]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

## Creando matrix con numpy

In [10]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Arryas usando arange

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0, 101, 20) # crea un array desde el 0 al 100 dando saltos de 20 en 20

array([  0,  20,  40,  60,  80, 100])

## Creando matrices con .zeros() y .ones()

In [14]:
np.zeros((2, 3))  # crea una matriz de 2 filas por 3 columnas

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## .linspace() function

In [17]:
array_lin = np.linspace(0, 10, 20)  # ? crea un array del 0 al 10 pero que contenga 20 valores separados equitativamente
array_lin

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [19]:
array_lin = np.linspace(0, 10, 11) 
array_lin

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [20]:
np.eye(5)  # La función eye en NumPy genera una matriz identidad de forma cuadrada con una diagonal de unos y ceros en el resto de los elementos. 
            # Esta función es útil en cálculos matriciales y en la resolución de sistemas de ecuaciones lineales.

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Generando numeros aleatorios

In [21]:
np.random.rand(1)  # genera un numero aleatorio entre 0 y 1

array([0.11095076])

In [22]:
np.random.rand(5, 3)  # ? Se le da una forma, aqui tiene 5 filas, 3 columnas

array([[0.7429814 , 0.18270919, 0.95896829],
       [0.90529778, 0.95707747, 0.28912688],
       [0.86743142, 0.77132943, 0.16564606],
       [0.11681086, 0.16766358, 0.05230202],
       [0.58908861, 0.1862921 , 0.63085074]])

In [23]:
np.random.randn(10) # .randn() genera números aleatorios con distribución normal estándar, también conocida como distribución Gaussiana o distribución de probabilidad normal.

array([ 0.38773645,  0.13459063,  0.86967626,  0.56123188, -2.8794436 ,
        2.26058802, -0.11126539,  1.17323134, -0.43749709, -1.15941839])

In [24]:
np.random.randint(0, 101, 20) # devuelve una lista de 20 numeros aleatorios ENTEROS, 

array([ 60,  16,  32,   5,  40,  52,  31,  74,  23,  79,   4,  71,  89,
        86,  41,  76,  32,  36,  17, 100])

In [25]:
np.random.randint(0, 101, (5,7))  # lo mismo de arriba pero con un "shape" de 5 filas, 7 columnas

array([[80, 50, 32, 52, 96, 38, 76],
       [97, 70, 10,  2, 27, 30, 96],
       [42, 95, 66, 74, 65, 90, 82],
       [ 7, 77, 73, 68, 56, 14, 47],
       [24,  7, 54, 26, 55, 71, 82]])

In [27]:
np.random.seed(42)  # ? .seed() La semilla es un valor que se usa para inicializar un generador de números aleatorios para que produzca una secuencia predecible de números. 
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [28]:
np.random.rand(4)  # ? Estos son diferentes a los de arriba porque NO tienen el seed.

array([0.15601864, 0.15599452, 0.05808361, 0.86617615])

### Otros

In [33]:
arr = np.arange(0, 25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [32]:
# arr.reshape(5, 4)  # ? Esto dara error, solo tiene espacio para 20 y el dataset es de 25 numeros
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [34]:
ranarr = np.random.randint(0, 101, 10)

In [35]:
ranarr

array([99, 23,  2, 21, 52,  1, 87, 29, 37,  1])

In [36]:
ranarr.max()

99

In [37]:
ranarr.min()

1

In [38]:
ranarr.argmax()  # ? Muestra el indice donde se encuentra el valor maximo 

0

In [39]:
ranarr.argmin()  # ? Muestra el indice donde se encuentra el valor minimo

5

In [41]:
ranarr.dtype

dtype('int64')

In [42]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [43]:
arr.shape

(25,)

In [44]:
arr = arr.reshape(5,5)

In [45]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [47]:
arr  = arr.reshape(25, 1)
arr

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])