In [1]:
import numpy as np 

In [2]:
arr = np.arange(0, 10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr + 5  # Inicia desde el numero 5 en lugar del 0

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
arr - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [5]:
arr + arr  # Tienen que tener el mismo tamaño ambos array, y aqui duplicara el valor de cada indice

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [6]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [10]:
arr / arr 

/tmp/ipykernel_1897/2663351161.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [11]:
1 / 0  # Recibimos un error de division 0 (porque usamos python normal)

ZeroDivisionError: division by zero

In [12]:
1 / arr  # ? Deberia mostrar un error de division 0 pero NO lo hace. 

/tmp/ipykernel_1897/1528351372.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [13]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [14]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [15]:
np.log(arr)

/tmp/ipykernel_1897/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [16]:
arr 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
arr.sum() # ? suma todos los valores dentro del array 

45

In [18]:
arr.mean()  # Devuelve la media del array 

4.5

In [19]:
arr.max()

9

In [20]:
arr.min()

0

In [21]:
arr.var() # Optenemos la varianza 

8.25

In [22]:
arr.std()  # Optenemos la desviacion estandar 

2.8722813232690143

In [24]:
arr2d = np.arange(0, 25).reshape(5, 5) # Pasamos de 1 fila y 25 columnas a 5 filas y 5 columnas
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
arr2d.sum()

300

In [26]:
arr2d.sum(axis=0)  # ? Axis 0, se refiere a las columnas (atraves de las filas)

array([50, 55, 60, 65, 70])

In [27]:
arr2d.sum(axis=1)  # ? Axis 1, se refiere a las filas (por toda la fila)

array([ 10,  35,  60,  85, 110])